"""add relationship between profile/record

Revision ID: db891aa9536b
Revises: c0d642d38585
Create Date: 2024-07-10 14:09:05.424452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db891aa9536b'
down_revision: Union[str, None] = 'c0d642d38585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recordevents_profile_id_fkey', 'recordevents', type_='foreignkey')
    op.create_foreign_key(None, 'recordevents', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recordevents', type_='foreignkey')
    op.create_foreign_key('recordevents_profile_id_fkey', 'recordevents', 'users', ['profile_id'], ['id'])
    # ### end Alembic commands ###
